sudo: required
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.6-dev
matrix:
  allow_failures:
    - python: "3.6"
    - python: "3.6-dev"
    - python: "nightly"
install:
- "pip install -r tests/requirements.txt"
script:
- py.test
